### ISSUE TITLE
refactor userDetails and tradingPartnerDetails in OnboardDetails

### ISSUE THREAD

**Issue by celber** [OpusCapita/user#13]
For now they are stringified JSON as MEDIUMTEXT what is inefficient and insecure. We already knwo what fields will be there so please refactor it to proper MySQL columns

**Comment by gr4per** [comment]
We are not going as the respective userDetails and tradingPartnerDetails are not in the user domain, so we cannot implement schema for them in user.
That is why we are storing and passign them through with black box approach.
