### ISSUE TITLE
User administration filtering incorrect

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#143]
The user filtering breaks in case that role constraints are added.
![image](https://user-images.githubusercontent.com/22681804/48755564-0cdf2400-ec96-11e8-9661-181bbe602b45.png)

Reported by Wilhelmsen user Patrizia.Cortese@wilhemsen.com
on stage.

Reproduced with John.Doeqncc.com on stage after updating UserHasRole constraints to 
c_wilhelmsenships-01/*;c_wilhelmsenships-12

```
mysql> mysql> select * from user.UserHasRole where userId like '%doe%';
+------------------+----------------+---------------------------------------------+--------------+-----------+---------------------+-----------+
| userId           | roleId         | constraints                                 | createdBy    | changedBy | createdOn           | changedOn |
+------------------+----------------+---------------------------------------------+--------------+-----------+---------------------+-----------+
| john.doe@ncc.com | customer-admin | c_wilhelmsenships-01/*;c_wilhelmsenships-12 | svc_supplier |           | 2018-02-20 15:04:01 | NULL      |
| john.doe@ncc.com | user           | c_wilhelmsenships-01/*;c_wilhelmsenships-12 | svc_supplier |           | 2018-02-20 15:04:01 | NULL      |
+------------------+----------------+---------------------------------------------+--------------+-----------+---------------------+-----------+
2 rows in set (0.01 sec)
```

**Comment by gr4per** [comment]
Expectation:
1) FIX
2) release to PROD
3) write unit test to prevent this

**Comment by gr4per** [comment]
Turns out it is not an issue after all.
All the users visible on Patrizia and john.doe views are in fact assigned to wilhelmsen on stage.
On dev / local issue was not reproducable at all, cause no users assigned to wilhelmsen.

**Comment by kwierchris** [comment]
I don't really understand what the current status of this ticket is.

**Comment by gr4per** [comment]
issue is pending Patrizia Corteses confirmation of the fix.

**Comment by kwierchris** [comment]
Confirmed.
