### ISSUE TITLE
Publish events on user updates

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#2]
We need to publish events via redis pub/sub whenever a user or userprofile is updated.
Listeners will then be able to subscribe and do whatever 

We might flag events additionally when status changed if some listeners only interested in lifecycle changes.

**Comment by kwierchris** [comment]
Example on how to do this from node: https://github.com/NodeRedis/node_redis#publish--subscribe

**Comment by kwierchris** [comment]
We have this now and can use it: https://www.npmjs.com/package/ocbesbn-redis-events
