### ISSUE TITLE
Add serviceDetails to onboardData

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#29]
Add new property
serviceDetails to userOnboardData
this needs to be generic json (String in DB)
and allow to set key values as
serviceName -> {...} // JSON with service specific configuration

First appliance:
in eInvoiceOnboarding workflow, when generating invitationCode / userOnboardData, also write serviceDetails entry to userOnboardData. This can then be read by eInvoiceSend service for any specific settings.

see https://github.com/OpusCapita/onboarding/issues/133

**Comment by kwierchris** [comment]
Fixed 2ec081e9e9c3b46d9700221001dbad805e359906
