### ISSUE TITLE
Add status to userOnboardData to prevent multi-use

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#30]
add status field, default "new"
once user is registered, update status to registered.
add status to userOnboardData api as search restriction param ?filter=status eq 'new'
and also filter=status in ['new', 'registered']

we will need that in order to prevent multiple usage of same invitation.

**Comment by kwierchris** [comment]
Made auth check if a user id was assigned to an invitation code requested. Multi use invitation codes will always return data without a user ID assigned (#47).
