### ISSUE TITLE
UI for assigning roles

### ISSUE THREAD

**Issue by StefanDywersant** [OpusCapita/user#54]
Create UI for assigning/removing roles to/from user.

Also create assignableRoles domain and proper api's. This will describe which roles user can assign based on current user roles.

**Comment by kwierchris** [comment]
...domain objects and api's for assigning (and removing) roles to user. What does this mean? All this is already present.

**Comment by StefanDywersant** [comment]
Sorry, I wasn't precise. The new domain object will be "assignableRole" which will describe which roles can be assigned based on current user roles.
