### ISSUE TITLE
User editor

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#56]
Administrators need a way to list users in a pageable table view.
This should be accessible via BNP Settings / Administration menu
Hence shared component.

Basically list all user records (user.User) in a table, at least include
id, email, first name, last name, status, roles, federation

For each we need actions like
-generate new password (which will send new temporary one via user.email to user)
-lock / unlock

**Comment by kwierchris** [comment]
Please ignore the *lock / unlock* feature for now.
