### ISSUE TITLE
Add user2role

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#6]
userId

roleId

These can be combined to composite primary key.
userId should be first as we will have cases where we query roleIds for userId, rarely the other way round.

Add the user.roles to user model and user api endpoint
it can be a simple array of strings and will also be mapped as claims to userinfo in auth

**Comment by gr4per** [comment]
Going to be used in 
https://github.com/OpusCapita/auth/issues/27

**Comment by kwierchris** [comment]
Should be available now.
