### ISSUE TITLE
Create demo user

### ISSUE THREAD

**Issue by alevchuk-sc** [OpusCapita/user#65]
For invoice service matching functionality we need new user "mark.matcher@musterkunden.de" which have a role "invoice-matcher".

**Comment by kwierchris** [comment]
You're free to create a PR with a db migration.

**Comment by blomqsu1** [comment]
I believe this is already implemented? At least we have the user mentioned here.

**Comment by alevchuk-sc** [comment]
> I believe this is already implemented? At least we have the user mentioned here.

Yes, it is. I guess issue could be closed.
