### ISSUE TITLE
Not able to remove role assignment from user

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/user#96]
I am logged in as ocadmin (on stage)
Trying to unassign supplier-admin role from tapani.oksala@opuscapita.com

Doesnt work, there is no delete button.

![image](https://user-images.githubusercontent.com/22681804/37143010-19bdd0aa-22ba-11e8-836b-a3b292b14c18.png)

**Comment by StefanDywersant** [comment]
There is a AssignableRole domain which defines which roles can be assigned by which roles (https://github.com/OpusCapita/user/issues/54).

Currently it looks like:
<img width="625" alt="zrzut ekranu 2018-03-09 o 11 28 53" src="https://user-images.githubusercontent.com/7136002/37203306-8b7ba892-238d-11e8-8419-e5751dd2dd3f.png">

**Comment by StefanDywersant** [comment]
Can you please review following list of owned/assignable roles relations?

```[
  {
    "ownedRoleId": "admin",
    "assignableRoleId": "admin"
  },
  {
    "ownedRoleId": "admin",
    "assignableRoleId": "supplier-admin"
  },
  {
    "ownedRoleId": "admin",
    "assignableRoleId": „invoice-inspector"
  },
  {
    "ownedRoleId": "admin",
    "assignableRoleId": „invoice-approver"
  },
  {
    "ownedRoleId": "admin",
    "assignableRoleId": „customer-admin"
  },
  {
    "ownedRoleId": "supplier-admin",
    "assignableRoleId": "supplier-admin"
  },
  {
    "ownedRoleId": "supplier-admin",
    "assignableRoleId": "supplier"
  },
  {
    "ownedRoleId": "customer-admin",
    "assignableRoleId": "customer-admin"
  }
]```

**Comment by kwierchris** [comment]
To me this looks good but I don't really understand the problem.

**Comment by StefanDywersant** [comment]
**admin** could not unassign **supplier-admin** role from given user because according to https://github.com/OpusCapita/user/issues/96#issuecomment-371775816 **admin** was not allowed to manipulate **supplier-admin** roles.

Following entry is missing in AssignableRole domain:
```
{
    "ownedRoleId": "admin",
    "assignableRoleId": "supplier-admin"
  },```

And not only this one, above I proposed full list of such relations.

**Comment by kwierchris** [comment]
Ah ok. So lgtm.

**Comment by gr4per** [comment]
But for taking away roles is it applicable ?
In any case, admin should be able to assign/unassign supplier-admin and customer-admin
(and probably everything as admin is exactly that: admin 😊 )

Von: Karol Maciaszek [mailto:notifications@github.com]
Gesendet: Freitag, 9. März 2018 11:33
An: OpusCapita/user <user@noreply.github.com>
Cc: Gräper Arne <Arne.Graeper@opuscapita.com>; Author <author@noreply.github.com>
Betreff: Re: [OpusCapita/user] Not able to remove role assignment from user (#96)


There is a AssignableRole domain which defines which roles can be assigned by which roles (#54<https://github.com/OpusCapita/user/issues/54>).

Currently it looks like:
[zrzut ekranu 2018-03-09 o 11 28 53]<https://user-images.githubusercontent.com/7136002/37203306-8b7ba892-238d-11e8-8419-e5751dd2dd3f.png>
